// src/frontend/music-qwik/src/app.tsx
import { $, component$, useStore } from '@builder.io/qwik';
import './app.css';
import Navbar from './components/navbar';
import NowPlaying from './components/now-playing';
import RecentlyPlayedList from './components/recently-played-list';
import RecommendationForm from './components/recommendation-form';
import RecommendationList from './components/recommendation-list';
import { Song } from './types/Song';

export const App = component$(() => {
  const recommendations = useStore<Song[]>([
    {
      songTitle: 'Song One',
      artistName: 'Artist One',
      albumName: 'Album One',
      albumCoverUrl: 'https://via.placeholder.com/50',
    },
    {
      songTitle: 'Song Two',
      artistName: 'Artist Two',
      albumName: 'Album Two',
      albumCoverUrl: 'https://via.placeholder.com/50',
    },
  ]);

  const addRecommendation = $((song: Song) => {
    recommendations.push(song);
  });

  return (
    <>
      <div class="app-bg" />
      <div class="app">
        <Navbar />
        <div class="main-content">
          <div class="left-column">
            <div class="now-playing-container">
              <NowPlaying />
            </div>
            <RecentlyPlayedList />
          </div>
          <div class="right-column">
            <div class="recommendation-form-container">
              <RecommendationForm onAddRecommendation={addRecommendation} />
            </div>
            <div class="recommendations-list-container">
              <RecommendationList recommendations={recommendations} />
            </div>
          </div>
        </div>
      </div>
    </>
  );
});

// src/frontend/music-react/src/App.tsx
import React, { useState } from 'react';
import './App.css';
import NowPlaying from './components/NowPlaying/index';
import RecentlyPlayedList from './components/RecentlyPlayedList/index';
import RecommendationForm from './components/RecommendationForm/index';
import RecommendationList from './components/RecommendationList/index';
import Navbar from './components/Navbar';
import { Song } from './types/Song';

const App: React.FC = () => {
  // State to hold the list of recommendations with initial mock data
  const [recommendations, setRecommendations] = useState<Song[]>([
    {
      songTitle: 'Song One',
      artistName: 'Artist One',
      albumName: 'Album One',
      albumCoverUrl: 'https://via.placeholder.com/50',
    },
    {
      songTitle: 'Song Two',
      artistName: 'Artist Two',
      albumName: 'Album Two',
      albumCoverUrl: 'https://via.placeholder.com/50',
    },
  ]);

  // Function to handle new recommendations
  const handleNewRecommendation = (songTitle: string) => {
    // Mock additional data
    const newRecommendation = {
      songTitle: songTitle,
      artistName: 'Mock Artist',
      albumName: 'Mock Album',
      albumCoverUrl: 'https://via.placeholder.com/50',
    };

    setRecommendations(prevRecommendations => [...prevRecommendations, newRecommendation]);
  };

  return (
    <>
      <div className="app-bg" />
      <div className="app">
        <Navbar />
        <div className="main-content">
          <div className="left-column">
            <div className="now-playing-container">
              <NowPlaying />
            </div>
            <RecentlyPlayedList />
          </div>
          <div className="right-column">
            <div className="recommendation-form-container">
              <RecommendationForm onRecommend={handleNewRecommendation} />
            </div>
            <div className="recommendations-list-container">
              <RecommendationList recommendations={recommendations} />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default App;
