// src/app/frontend/music/music-angular/src/app/components/now-playing/now-playing.component.ts
import { Component, computed, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MusicService } from '../../../services/music.service';
import { formatRelativeTime } from '../../../utils/formatters';
import { getProcessedArtworkUrl } from '../../../utils/image-processing';
import { openUrlInNewTab } from '../../../utils/navigation';
import { SourceIndicatorComponent } from '../source-indicator/source-indicator.component';

@Component({
  selector: 'app-now-playing',
  standalone: true,
  imports: [CommonModule, SourceIndicatorComponent],
  templateUrl: './now-playing.component.html',
  styleUrl: './now-playing.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class NowPlayingComponent {
  constructor(public musicService: MusicService) {}

  readonly relativeTime = computed(() => {
    const nowPlaying = this.musicService.nowPlaying();
    return nowPlaying?.processedTimestamp
      ? formatRelativeTime(nowPlaying.processedTimestamp)
      : '';
  });

  readonly artworkUrl = computed(() => {
    const nowPlaying = this.musicService.nowPlaying();
    return getProcessedArtworkUrl(nowPlaying?.artworkUrl, '300x300');
  });

  handleAlbumArtClick(): void {
    const nowPlaying = this.musicService.nowPlaying();
    openUrlInNewTab(nowPlaying?.url);
  }

  getTimestampTitle(): string {
    const nowPlaying = this.musicService.nowPlaying();
    return nowPlaying?.processedTimestamp
      ? `Played: ${new Date(nowPlaying.processedTimestamp).toLocaleString()}`
      : '';
  }
}


@if (musicService.loading() && !musicService.nowPlaying()) {
  <div class="nowPlayingComponent">
    <div class="albumArtContainer">
      <div class="nowPlayingSkeletonImg skeletonLoader"></div>
    </div>
    <div class="nowPlayingComponentTextContainer">
      <h1>Mario's Now Playing</h1>
      <div class="nowPlayingComponentText">
        <div class="songTitleContainer">
          <div class="skeletonLoader" style="width: 14px; height: 14px; border-radius: 50%; flex-shrink: 0;"></div>
          <div class="nowPlayingSkeletonTitle skeletonLoader"></div>
        </div>
        <div class="nowPlayingSkeletonArtist skeletonLoader"></div>
        <div class="nowPlayingSkeletonAlbum skeletonLoader"></div>
        <div class="nowPlayingSkeletonTimestamp skeletonLoader"></div>
      </div>
    </div>
  </div>
} @else if (musicService.error() && !musicService.nowPlaying()) {
  <div class="nowPlayingComponent">
    <img [src]="artworkUrl()" alt="Error Album Art" />
    <div class="nowPlayingComponentTextContainer">
      <h1>Mario's Now Playing</h1>
      <div class="nowPlayingComponentText">
        <h2>Unable to load music data</h2>
        <p>{{ musicService.error() }}</p>
      </div>
    </div>
  </div>
} @else {
  <div class="nowPlayingComponent">
    <div class="albumArtContainer">
      <img
        [src]="artworkUrl()"
        [alt]="musicService.nowPlaying()?.albumName || 'Album' + ' Art'"
        (click)="handleAlbumArtClick()"
        [style.cursor]="musicService.nowPlaying()?.url ? 'pointer' : 'default'"
        [title]="musicService.nowPlaying()?.url ? 'Click to open ' + (musicService.nowPlaying()?.name || '') + ' in Apple Music' : ''"
      />
    </div>
    <div class="nowPlayingComponentTextContainer">
      <div class="nowPlayingHeader">
        <h1>Mario's Now Playing</h1>
      </div>
      <div class="nowPlayingComponentText">
        <div class="songTitleContainer">
          <app-source-indicator
            [source]="musicService.nowPlaying()?.source"
            size="small"
            [url]="musicService.nowPlaying()?.url"
          />
          <h2 [title]="musicService.nowPlaying()?.name || 'No song playing'">
            {{ musicService.nowPlaying()?.name || 'No song playing' }}
          </h2>
        </div>
        <p [title]="musicService.nowPlaying()?.artistName || 'Unknown Artist'">
          {{ musicService.nowPlaying()?.artistName || 'Unknown Artist' }}
        </p>
        <p [title]="musicService.nowPlaying()?.albumName || 'Unknown Album'">
          {{ musicService.nowPlaying()?.albumName || 'Unknown Album' }}
        </p>
        @if (relativeTime()) {
          <span
            class="nowPlayingTimestamp"
            [title]="getTimestampTitle()"
          >
            {{ relativeTime() }}
          </span>
        }
      </div>
    </div>
  </div>
}

// src/app/frontend/music/music-vue/src/components/NowPlaying.vue
<template>
  <div v-if="loading && !nowPlaying" :class="styles.nowPlayingComponent">
    <div :class="styles.albumArtContainer">
      <div :class="[styles.nowPlayingSkeletonImg, styles.skeletonLoader]"></div>
    </div>
    <div :class="styles.nowPlayingComponentTextContainer">
      <h1>Mario's Now Playing</h1>
      <div :class="styles.nowPlayingComponentText">
        <div :class="styles.songTitleContainer">
          <div
            :class="styles.skeletonLoader"
            style="width: 14px; height: 14px; border-radius: 50%; flex-shrink: 0"
          ></div>
          <div
            :class="[styles.nowPlayingSkeletonTitle, styles.skeletonLoader]"
          ></div>
        </div>
        <div
          :class="[styles.nowPlayingSkeletonArtist, styles.skeletonLoader]"
        ></div>
        <div :class="[styles.nowPlayingSkeletonAlbum, styles.skeletonLoader]"></div>
        <div
          :class="[styles.nowPlayingSkeletonTimestamp, styles.skeletonLoader]"
        ></div>
      </div>
    </div>
  </div>

  <div v-else-if="error && !nowPlaying" :class="styles.nowPlayingComponent">
    <img :src="getProcessedArtworkUrl(undefined)" alt="Error Album Art" />
    <div :class="styles.nowPlayingComponentTextContainer">
      <h1>Mario's Now Playing</h1>
      <div :class="styles.nowPlayingComponentText">
        <h2>Unable to load music data</h2>
        <p>{{ error }}</p>
      </div>
    </div>
  </div>

  <div v-else :class="styles.nowPlayingComponent">
    <div :class="styles.albumArtContainer">
      <img
        :src="getProcessedArtworkUrl(nowPlaying?.artworkUrl, '300x300')"
        :alt="`${nowPlaying?.albumName || 'Album'} Art`"
        :style="{ cursor: nowPlaying?.url ? 'pointer' : 'default' }"
        :title="
          nowPlaying?.url ? `Click to open ${nowPlaying.name} in Apple Music` : ''
        "
        @click="handleAlbumArtClick"
      />
    </div>
    <div :class="styles.nowPlayingComponentTextContainer">
      <div :class="styles.nowPlayingHeader">
        <h1>Mario's Now Playing</h1>
      </div>
      <div :class="styles.nowPlayingComponentText">
        <div :class="styles.songTitleContainer">
          <SourceIndicator
            :source="nowPlaying?.source"
            size="small"
            :url="nowPlaying?.url"
          />
          <h2 :title="nowPlaying?.name || 'No song playing'">
            {{ nowPlaying?.name || "No song playing" }}
          </h2>
        </div>
        <p :title="nowPlaying?.artistName || 'Unknown Artist'">
          {{ nowPlaying?.artistName || "Unknown Artist" }}
        </p>
        <p :title="nowPlaying?.albumName || 'Unknown Album'">
          {{ nowPlaying?.albumName || "Unknown Album" }}
        </p>
        <span
          v-if="relativeTime"
          :class="styles.nowPlayingTimestamp"
          :title="`Played: ${playedAtDisplay}`"
        >
          {{ relativeTime }}
        </span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { useMusicStore } from "../composables/useMusicStore";
import { formatRelativeTime } from "../utils/formatters";
import { getProcessedArtworkUrl } from "../utils/imageProcessing";
import { openUrlInNewTab } from "../utils/navigation";
import SourceIndicator from "./SourceIndicator.vue";
import styles from "./NowPlaying.module.css";

const musicStore = useMusicStore();

const nowPlaying = computed(() => musicStore.nowPlaying.value);
const loading = computed(() => musicStore.loading.value);
const error = computed(() => musicStore.error.value);

const relativeTime = computed(() => {
  if (!nowPlaying.value?.processedTimestamp) {
    return "";
  }
  return formatRelativeTime(nowPlaying.value.processedTimestamp);
});

const playedAtDisplay = computed(() => {
  if (!nowPlaying.value?.processedTimestamp) {
    return "";
  }
  return new Date(nowPlaying.value.processedTimestamp).toLocaleString();
});

const handleAlbumArtClick = () => {
  openUrlInNewTab(nowPlaying.value?.url);
};
</script>
