// src/app/frontend/music/music-react/src/components/SourceIndicator/SourceIndicator.tsx
import { memo } from 'react';
import { MusicSource, getMusicSourceDisplayName } from '../../types/MusicSource';
import { openUrlInNewTab } from '../../utils/navigation';
import { AppleMusicIcon, SpotifyIcon } from '../Icons/Icons';
import styles from './SourceIndicator.module.css';

interface SourceIndicatorProps {
  source?: MusicSource;
  size?: 'small' | 'large';
  url?: string;
  onClick?: () => void;
}

/**
 * SourceIndicator displays a cute, minimal badge indicating the music platform source
 * Positioned as an overlay on album artwork
 * Defaults to Apple Music if no source is specified (original data source)
 */
export const SourceIndicator = memo(({ source, size = 'small', url, onClick }: SourceIndicatorProps) => {
  // Default to Apple Music if no source is provided (original data source)
  // Only hide indicator if explicitly set to 'unknown'
  const actualSource: MusicSource = source && source !== 'unknown' ? source : 'apple';

  const displayName = getMusicSourceDisplayName(actualSource);
  const sizeClass = size === 'large' ? styles.large : styles.small;

  const handleClick = () => {
    if (url && onClick) {
      onClick();
    } else {
      openUrlInNewTab(url);
    }
  };

  return (
    <div
      className={`${styles.indicator} ${sizeClass} ${styles[actualSource]}`}
      title={url ? `Click to open in ${displayName}` : displayName}
      aria-label={`Source: ${displayName}`}
      onClick={handleClick}
      style={{
        cursor: url ? 'pointer' : 'default',
        pointerEvents: url ? 'auto' : 'none'
      }}
    >
      {actualSource === 'apple' && <AppleMusicIcon />}
      {actualSource === 'spotify' && <SpotifyIcon />}
    </div>
  );
});

SourceIndicator.displayName = 'SourceIndicator';

// src/app/frontend/music/music-angular/src/app/components/source-indicator/source-indicator.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MusicSource, getMusicSourceDisplayName } from '../../../models/music-source';
import { openUrlInNewTab } from '../../../utils/navigation';
import { AppleMusicIconComponent } from '../icons/icons.component';
import { SpotifyIconComponent } from '../icons/icons.component';

@Component({
  selector: 'app-source-indicator',
  standalone: true,
  imports: [CommonModule, AppleMusicIconComponent, SpotifyIconComponent],
  templateUrl: './source-indicator.component.html',
  styleUrl: './source-indicator.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SourceIndicatorComponent {
  @Input() source?: MusicSource;
  @Input() size: 'small' | 'large' = 'small';
  @Input() url?: string;

  get actualSource(): MusicSource {
    // Default to Apple Music if no source is provided (original data source)
    // Only hide indicator if explicitly set to 'unknown'
    return this.source && this.source !== 'unknown' ? this.source : 'apple';
  }

  get displayName(): string {
    return getMusicSourceDisplayName(this.actualSource);
  }

  handleClick(): void {
    if (this.url) {
      openUrlInNewTab(this.url);
    }
  }
}


<div
  class="indicator"
  [class.small]="size === 'small'"
  [class.large]="size === 'large'"
  [class.apple]="actualSource === 'apple'"
  [class.spotify]="actualSource === 'spotify'"
  [title]="url ? 'Click to open in ' + displayName : displayName"
  [attr.aria-label]="'Source: ' + displayName"
  (click)="handleClick()"
  [style.cursor]="url ? 'pointer' : 'default'"
  [style.pointer-events]="url ? 'auto' : 'none'"
>
  @if (actualSource === 'apple') {
    <app-apple-music-icon />
  }
  @if (actualSource === 'spotify') {
    <app-spotify-icon />
  }
</div>
