// src/frontend/music-preact/src/components/RecommendationForm/index.tsx
import { useState } from 'preact/hooks';
import './index.css';

type RecommendationFormProps = {
    onRecommend: (songTitle: string) => void;
};

const RecommendationForm = ({ onRecommend }: RecommendationFormProps) => {
    const [songTitle, setSongTitle] = useState('');

    const handleSubmit = (event: Event) => {
        event.preventDefault();
        onRecommend(songTitle);
        setSongTitle('');
    };

    return (
        <div className="recommendation-form-component styled-container">
            <h1>Recommend a Song</h1>
            <form onSubmit={handleSubmit as any}>
                <input
                    type="text"
                    value={songTitle}
                    onChange={(e) => setSongTitle((e.target as HTMLInputElement).value)}
                    placeholder="Find a song on Apple Music..."
                    required
                />
                <button type="submit">Recommend</button>
            </form>
        </div>
    );
};

export default RecommendationForm;

// src/frontend/music-solid/src/components/RecommendationForm/index.tsx
import { createSignal } from 'solid-js';
import './index.css';

type RecommendationFormProps = {
    onRecommend: (songTitle: string) => void;
};

const RecommendationForm = (props: RecommendationFormProps) => {
    const [songTitle, setSongTitle] = createSignal('');

    const handleSubmit = (event: Event) => {
        event.preventDefault();
        props.onRecommend(songTitle());
        setSongTitle('');
    };

    return (
        <div class="recommendation-form-component styled-container">
            <h1>Recommend a Song</h1>
            <form onSubmit={handleSubmit}>
                <input
                    type="text"
                    value={songTitle()}
                    onInput={(e) => setSongTitle(e.currentTarget.value)}
                    placeholder="Find a song on Apple Music..."
                    required
                />
                <button type="submit">Recommend</button>
            </form>
        </div>
    );
};

export default RecommendationForm;
