// src/app/frontend/music/music-next/src/components/RecentlyPlayedList/components/CarouselRow.tsx
import React, {
  memo,
  useRef,
  useState,
  useEffect,
  useCallback,
  useMemo,
} from "react";
import { AppleMusicSong } from "../../../models/AppleMusicSong";
import styles from "../styles/CarouselRow.module.css";
import SongItem from "./SongItem";

interface CarouselRowProps {
  songs: AppleMusicSong[];
  settings: {
    speed: number; // Duration in ms for one complete cycle
    direction: "left" | "right"; // Direction of movement
  };
  rowName: string;
}

/**
 * Carousel row component using CSS animations for seamless infinite scrolling
 * with pause on hover
 */
const CarouselRow: React.FC<CarouselRowProps> = ({
  songs,
  settings,
  rowName,
}) => {
  const trackRef = useRef<HTMLDivElement>(null);
  const [isHovered, setIsHovered] = useState(false);
  const [contentWidth, setContentWidth] = useState(0);

  // Memoize duplicated songs to prevent recalculation on every render
  // Duplicate songs multiple times for seamless infinite scroll
  // Need enough duplicates to ensure seamless looping
  const duplicatedSongs = useMemo(
    () => [...songs, ...songs, ...songs],
    [songs],
  );

  // Calculate content width (width of one set of songs)
  const updateContentWidth = useCallback(() => {
    if (trackRef.current) {
      const items = trackRef.current.querySelectorAll("[data-carousel-item]");
      if (items.length > 0) {
        let totalWidth = 0;
        const thirdLength = items.length / 3;
        for (let i = 0; i < thirdLength; i++) {
          totalWidth += (items[i] as HTMLElement).offsetWidth;
        }
        setContentWidth(totalWidth);
      }
    }
  }, []);

  useEffect(() => {
    // Wait for items to render, then measure
    const timeoutId = setTimeout(() => {
      updateContentWidth();
    }, 100);

    window.addEventListener("resize", updateContentWidth);
    return () => {
      clearTimeout(timeoutId);
      window.removeEventListener("resize", updateContentWidth);
    };
  }, [songs, updateContentWidth]);

  // Update CSS custom properties for animation
  useEffect(() => {
    if (trackRef.current && contentWidth > 0) {
      const track = trackRef.current;
      const duration = settings.speed / 1000; // Convert ms to seconds

      track.style.setProperty("--carousel-content-width", `${contentWidth}px`);
      track.style.setProperty("--carousel-duration", `${duration}s`);
    }
  }, [contentWidth, settings.speed]);

  // Memoize mouse event handlers to prevent recreation on every render
  // Must be before any early returns (React hooks rule)
  const handleMouseEnter = useCallback(() => {
    setIsHovered(true);
  }, []);

  const handleMouseLeave = useCallback(() => {
    setIsHovered(false);
  }, []);

  if (songs.length === 0) {
    return null;
  }

  // Determine animation class based on direction
  const animationClass =
    settings.direction === "right"
      ? styles.carouselTrackRight
      : styles.carouselTrackLeft;

  return (
    <div
      className={styles.recentlyPlayedListRow}
      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}
      role="region"
      aria-label={`${rowName} carousel of recently played songs`}
      aria-live="polite"
    >
      <div className={styles.carouselContainer}>
        <div
          ref={trackRef}
          className={`${styles.carouselTrack} ${animationClass} ${isHovered ? styles.carouselTrackPaused : ""}`}
          aria-hidden="false"
        >
          {duplicatedSongs.map((song, index) => (
            <div
              key={`${rowName}-${song.id}-${index}`}
              data-carousel-item
              className={styles.carouselItem}
            >
              <SongItem song={song} index={index} rowName={rowName} />
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default memo(CarouselRow);

// src/app/frontend/music/music-vue/src/components/recently-played/CarouselRow.vue
<template>
  <div
    v-if="songs.length > 0"
    :class="styles.recentlyPlayedListRow"
    :aria-label="`${rowName} carousel of recently played songs`"
    aria-live="polite"
    role="region"
    @mouseenter="isHovered = true"
    @mouseleave="isHovered = false"
  >
    <div :class="styles.carouselContainer">
      <div
        ref="trackRef"
        :class="[
          styles.carouselTrack,
          settings.direction === 'right'
            ? styles.carouselTrackRight
            : styles.carouselTrackLeft,
          isHovered ? styles.carouselTrackPaused : '',
        ]"
      >
        <div
          v-for="(song, index) in duplicatedSongs"
          :key="`${rowName}-${song.id}-${index}`"
          :class="styles.carouselItem"
          data-carousel-item
        >
          <SongItem :song="song" :index="index" :row-name="rowName" />
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import {
  computed,
  nextTick,
  onMounted,
  onUnmounted,
  ref,
  watch,
} from "vue";
import type { AppleMusicSong } from "../../models/AppleMusicSong";
import type { CarouselSettings } from "../../composables/useCarouselSettings";
import SongItem from "./SongItem.vue";
import styles from "./CarouselRow.module.css";

interface Props {
  songs: AppleMusicSong[];
  settings: CarouselSettings;
  rowName: string;
}

const props = defineProps<Props>();

const trackRef = ref<HTMLDivElement | null>(null);
const isHovered = ref(false);
const contentWidth = ref(0);
const measureTimeoutId = ref<number | null>(null);

const duplicatedSongs = computed(() => {
  return [...props.songs, ...props.songs, ...props.songs];
});

const updateContentWidth = () => {
  if (!trackRef.value) {
    return;
  }

  const items = trackRef.value.querySelectorAll("[data-carousel-item]");
  if (items.length === 0) {
    contentWidth.value = 0;
    return;
  }

  let totalWidth = 0;
  const thirdLength = items.length / 3;
  for (let index = 0; index < thirdLength; index += 1) {
    totalWidth += (items[index] as HTMLElement).offsetWidth;
  }
  contentWidth.value = totalWidth;
};

onMounted(() => {
  measureTimeoutId.value = window.setTimeout(() => {
    void nextTick(updateContentWidth);
  }, 100);

  window.addEventListener("resize", updateContentWidth);
});

onUnmounted(() => {
  if (measureTimeoutId.value !== null) {
    window.clearTimeout(measureTimeoutId.value);
    measureTimeoutId.value = null;
  }
  window.removeEventListener("resize", updateContentWidth);
});

watch(
  () => props.songs,
  async () => {
    await nextTick();
    if (measureTimeoutId.value !== null) {
      window.clearTimeout(measureTimeoutId.value);
    }
    measureTimeoutId.value = window.setTimeout(updateContentWidth, 100);
  },
  { deep: true, immediate: true },
);

watch(
  [contentWidth, () => props.settings.speed],
  ([width, speed]) => {
    if (!trackRef.value || width <= 0) {
      return;
    }
    const duration = speed / 1000;
    trackRef.value.style.setProperty("--carousel-content-width", `${width}px`);
    trackRef.value.style.setProperty("--carousel-duration", `${duration}s`);
  },
  { immediate: true },
);
</script>
