// src/app/frontend/music/music-angular/src/app/components/recently-played-list/components/song-item/song-item.component.ts
import { Component, Input, ChangeDetectionStrategy, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AppleMusicSong } from '../../../../../models/apple-music-song';
import { getProcessedArtworkUrl } from '../../../../../utils/image-processing';
import { openUrlInNewTab } from '../../../../../utils/navigation';
import { SourceIndicatorComponent } from '../../../source-indicator/source-indicator.component';

@Component({
  selector: 'app-song-item',
  standalone: true,
  imports: [CommonModule, SourceIndicatorComponent],
  templateUrl: './song-item.component.html',
  styleUrl: './song-item.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SongItemComponent {
  @Input({ required: true }) song!: AppleMusicSong;
  @Input({ required: true }) index!: number;
  @Input({ required: true }) rowName!: string;

  readonly imageError = signal(false);

  readonly artworkUrl = computed(() => getProcessedArtworkUrl(this.song?.artworkUrl));

  // Expose getProcessedArtworkUrl to template
  getProcessedArtworkUrl = getProcessedArtworkUrl;

  handleImageError(): void {
    this.imageError.set(true);
  }

  handleAlbumArtClick(): void {
    openUrlInNewTab(this.song.url);
  }
}


<div [attr.data-carousel-item]="index">
  <div class="song">
    <div class="albumArtContainer">
      <img
        [src]="imageError() ? getProcessedArtworkUrl(undefined) : artworkUrl()"
        [alt]="song.name + ' Album Cover'"
        [title]="song.url ? 'Click to open ' + song.name + ' in Apple Music' : song.name + ' by ' + song.artistName"
        (error)="handleImageError()"
        (click)="handleAlbumArtClick()"
        [style.cursor]="song.url ? 'pointer' : 'default'"
      />
    </div>
    <div class="songTextContainer">
      <div class="songTitleContainer">
        <app-source-indicator [source]="song.source" size="small" [url]="song.url" />
        <h3 [title]="song.name">{{ song.name }}</h3>
      </div>
      <p [title]="song.artistName + ' - ' + song.albumName">
        {{ song.artistName }} - {{ song.albumName }}
      </p>
    </div>
  </div>
</div>

// src/app/frontend/music/music-vue/src/components/recently-played/SongItem.vue
<template>
  <div>
    <div :class="styles.song">
      <div :class="styles.albumArtContainer">
        <img
          :src="imageError ? getProcessedArtworkUrl(undefined) : artworkUrl"
          :alt="`${song.name} Album Cover`"
          :title="
            song.url
              ? `Click to open ${song.name} in Apple Music`
              : `${song.name} by ${song.artistName}`
          "
          :style="{ cursor: song.url ? 'pointer' : 'default' }"
          @error="handleImageError"
          @click="handleAlbumArtClick"
        />
      </div>
      <div :class="styles.songTextContainer">
        <div :class="styles.songTitleContainer">
          <SourceIndicator :source="song.source" size="small" :url="song.url" />
          <h3 :title="song.name">{{ song.name }}</h3>
        </div>
        <p :title="`${song.artistName} - ${song.albumName}`">
          {{ song.artistName }} - {{ song.albumName }}
        </p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";
import type { AppleMusicSong } from "../../models/AppleMusicSong";
import { getProcessedArtworkUrl } from "../../utils/imageProcessing";
import { openUrlInNewTab } from "../../utils/navigation";
import SourceIndicator from "../SourceIndicator.vue";
import styles from "./SongItem.module.css";

interface Props {
  song: AppleMusicSong;
  index: number;
  rowName: string;
}

const props = defineProps<Props>();
const imageError = ref(false);

const artworkUrl = computed(() => {
  return getProcessedArtworkUrl(props.song.artworkUrl);
});

const handleImageError = () => {
  imageError.value = true;
};

const handleAlbumArtClick = () => {
  openUrlInNewTab(props.song.url);
};
</script>
