// src/app/frontend/music/music-angular/src/app/components/recently-played-list/components/carousel-row/carousel-row.component.ts
import { Component, Input, OnInit, AfterViewInit, OnDestroy, ChangeDetectionStrategy, ElementRef, ViewChild, signal, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AppleMusicSong } from '../../../../../models/apple-music-song';
import { SongItemComponent } from '../song-item/song-item.component';

interface CarouselSettings {
  speed: number; // Duration in ms for one complete cycle
  direction: 'left' | 'right'; // Direction of movement
}

@Component({
  selector: 'app-carousel-row',
  standalone: true,
  imports: [CommonModule, SongItemComponent],
  templateUrl: './carousel-row.component.html',
  styleUrl: './carousel-row.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class CarouselRowComponent implements OnInit, AfterViewInit, OnDestroy, OnChanges {
  @Input({ required: true }) songs!: AppleMusicSong[];
  @Input({ required: true }) settings!: CarouselSettings;
  @Input({ required: true }) rowName!: string;
  @ViewChild('trackRef', { static: false }) trackRef?: ElementRef<HTMLDivElement>;

  readonly isHovered = signal(false);
  readonly contentWidth = signal(0);

  private resizeListener?: () => void;

  // Duplicate songs multiple times for seamless infinite scroll
  get duplicatedSongs(): AppleMusicSong[] {
    return this.songs ? [...this.songs, ...this.songs, ...this.songs] : [];
  }

  ngOnInit(): void {
    // Component initialized
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['songs'] && !changes['songs'].firstChange && this.trackRef) {
      setTimeout(() => {
        this.updateContentWidth();
      }, 100);
    }
  }

  ngAfterViewInit(): void {
    // Use a small delay to ensure DOM is ready
    setTimeout(() => {
      this.updateContentWidth();
    }, 100);

    this.resizeListener = () => {
      this.updateContentWidth();
    };
    window.addEventListener('resize', this.resizeListener);
  }

  ngOnDestroy(): void {
    if (this.resizeListener) {
      window.removeEventListener('resize', this.resizeListener);
    }
  }

  private updateContentWidth(): void {
    if (this.trackRef?.nativeElement) {
      const items = this.trackRef.nativeElement.querySelectorAll('[data-carousel-item]');
      if (items.length > 0) {
        let totalWidth = 0;
        const thirdLength = items.length / 3;
        for (let i = 0; i < thirdLength; i++) {
          totalWidth += (items[i] as HTMLElement).offsetWidth;
        }
        this.contentWidth.set(totalWidth);
        this.updateCSSProperties();
      }
    }
  }

  private updateCSSProperties(): void {
    if (this.trackRef?.nativeElement && this.contentWidth() > 0) {
      const track = this.trackRef.nativeElement;
      const duration = this.settings.speed / 1000; // Convert ms to seconds

      track.style.setProperty('--carousel-content-width', `${this.contentWidth()}px`);
      track.style.setProperty('--carousel-duration', `${duration}s`);
    }
  }

  onMouseEnter(): void {
    this.isHovered.set(true);
  }

  onMouseLeave(): void {
    this.isHovered.set(false);
  }

  get animationClass(): string {
    return this.settings.direction === 'right' ? 'carousel-track-right' : 'carousel-track-left';
  }

  trackByIndex(index: number, song: AppleMusicSong): string {
    return `${this.rowName}-${song.id}-${index}`;
  }
}


@if (songs.length > 0) {
  <div
    class="recentlyPlayedListRow"
    (mouseenter)="onMouseEnter()"
    (mouseleave)="onMouseLeave()"
  >
    <div class="carouselContainer">
      <div
        #trackRef
        class="carouselTrack"
        [class.carouselTrackLeft]="settings.direction === 'left'"
        [class.carouselTrackRight]="settings.direction === 'right'"
        [class.carouselTrackPaused]="isHovered()"
      >
        @for (song of duplicatedSongs; track trackByIndex($index, song)) {
          <div class="carouselItem">
            <app-song-item
              [song]="song"
              [index]="$index"
              [rowName]="rowName"
            />
          </div>
        }
      </div>
    </div>
  </div>
}

// src/app/frontend/music/music-react/src/components/RecentlyPlayedList/components/CarouselRow.tsx
import React, { memo, useRef, useState, useEffect, useCallback } from "react";
import { AppleMusicSong } from "../../../models/AppleMusicSong";
import styles from "../styles/CarouselRow.module.css";
import SongItem from "./SongItem";

interface CarouselRowProps {
  songs: AppleMusicSong[];
  settings: {
    speed: number; // Duration in ms for one complete cycle
    direction: "left" | "right"; // Direction of movement
  };
  rowName: string;
}

/**
 * Carousel row component using CSS animations for seamless infinite scrolling
 * with pause on hover
 */
const CarouselRow: React.FC<CarouselRowProps> = ({
  songs,
  settings,
  rowName,
}) => {
  const trackRef = useRef<HTMLDivElement>(null);
  const [isHovered, setIsHovered] = useState(false);
  const [contentWidth, setContentWidth] = useState(0);

  // Duplicate songs multiple times for seamless infinite scroll
  // Need enough duplicates to ensure seamless looping
  const duplicatedSongs = [...songs, ...songs, ...songs];

  // Calculate content width (width of one set of songs)
  const updateContentWidth = useCallback(() => {
    if (trackRef.current) {
      const items = trackRef.current.querySelectorAll("[data-carousel-item]");
      if (items.length > 0) {
        let totalWidth = 0;
        const thirdLength = items.length / 3;
        for (let i = 0; i < thirdLength; i++) {
          totalWidth += (items[i] as HTMLElement).offsetWidth;
        }
        setContentWidth(totalWidth);
      }
    }
  }, []);

  useEffect(() => {
    // Wait for items to render, then measure
    const timeoutId = setTimeout(() => {
      updateContentWidth();
    }, 100);

    window.addEventListener("resize", updateContentWidth);
    return () => {
      clearTimeout(timeoutId);
      window.removeEventListener("resize", updateContentWidth);
    };
  }, [songs, updateContentWidth]);

  // Update CSS custom properties for animation
  useEffect(() => {
    if (trackRef.current && contentWidth > 0) {
      const track = trackRef.current;
      const duration = settings.speed / 1000; // Convert ms to seconds

      track.style.setProperty("--carousel-content-width", `${contentWidth}px`);
      track.style.setProperty("--carousel-duration", `${duration}s`);
    }
  }, [contentWidth, settings.speed]);

  if (songs.length === 0) {
    return null;
  }

  // Determine animation class based on direction
  const animationClass =
    settings.direction === "right"
      ? styles.carouselTrackRight
      : styles.carouselTrackLeft;

  return (
    <div
      className={styles.recentlyPlayedListRow}
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
    >
      <div className={styles.carouselContainer}>
        <div
          ref={trackRef}
          className={`${styles.carouselTrack} ${animationClass} ${isHovered ? styles.carouselTrackPaused : ""}`}
        >
          {duplicatedSongs.map((song, index) => (
            <div
              key={`${rowName}-${song.id}-${index}`}
              data-carousel-item
              className={styles.carouselItem}
            >
              <SongItem song={song} index={index} rowName={rowName} />
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default memo(CarouselRow);
