// src/app/frontend/music/music-vue/src/components/recently-played/SkeletonLoader.vue
<template>
  <div :class="styles.recentlyPlayedSkeletonContainer">
    <div
      v-for="row in skeletonRows"
      :key="`skeleton-row-${row}`"
      :class="styles.recentlyPlayedSkeletonRow"
    >
      <div
        v-for="item in skeletonItems"
        :key="`skeleton-${row}-${item}`"
        :class="styles.recentlyPlayedSkeletonSong"
      >
        <div
          :class="[styles.recentlyPlayedSkeletonImg, styles.skeletonLoader]"
        ></div>
        <div :class="styles.recentlyPlayedSkeletonText">
          <div
            :class="[styles.recentlyPlayedSkeletonTitle, styles.skeletonLoader]"
          ></div>
          <div
            :class="[
              styles.recentlyPlayedSkeletonSubtitle,
              styles.skeletonLoader,
            ]"
          ></div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import styles from "./SkeletonLoader.module.css";

const skeletonRows = [1, 2, 3];
const skeletonItems = [1, 2, 3, 4];
</script>

// src/app/frontend/music/music-angular/src/app/components/recently-played-list/components/skeleton-loader/skeleton-loader.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-skeleton-loader',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './skeleton-loader.component.html',
  styleUrl: './skeleton-loader.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SkeletonLoaderComponent {
  readonly skeletonItems = Array(4).fill(null);
  readonly rows = [1, 2, 3];
}


<div class="recentlyPlayedSkeletonContainer">
  @for (rowNum of rows; track rowNum) {
    <div class="recentlyPlayedSkeletonRow">
      @for (item of skeletonItems; track $index) {
        <div class="recentlyPlayedSkeletonSong">
          <div class="recentlyPlayedSkeletonImg skeletonLoader"></div>
          <div class="recentlyPlayedSkeletonText">
            <div class="recentlyPlayedSkeletonTitle skeletonLoader"></div>
            <div class="recentlyPlayedSkeletonSubtitle skeletonLoader"></div>
          </div>
        </div>
      }
    </div>
  }
</div>
