// src/frontend/music-vue/src/components/RecommendationForm.vue
<template>
    <div class="recommendation-form-modal">
        <h1>Recommend a Song</h1>
        <form @submit.prevent="handleSubmit">
            <input type="text" v-model="songTitle" placeholder="Find a song on Apple Music..." required />
            <button type="submit">Recommend</button>
        </form>
    </div>
</template>
  
<script lang="ts">
import { ref } from 'vue';

export default {
    name: 'RecommendationForm',
    props: {
        onRecommend: {
            type: Function,
            required: true,
        },
    },
    setup(props) {
        const songTitle = ref('');

        const handleSubmit = () => {
            props.onRecommend(songTitle.value);
            songTitle.value = '';
        };

        return { songTitle, handleSubmit };
    },
};
</script>
  
<style>
.recommendation-form-modal {
    background: rgba(50, 50, 50, 0.6);
    color: aliceblue;
    padding: 20px;
    border-radius: 15px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    max-width: 600px;
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    box-shadow: inset 0 4px 8px rgba(0, 0, 0, 0.1);
}

.recommendation-form-modal h1 {
    width: 100%;
    text-align: left;
    margin-top: 0;
    margin-bottom: 10px;
}

.recommendation-form-modal form {
    width: 100%;
    display: flex;
}

.recommendation-form-modal input[type="text"] {
    padding: 10px 15px;
    width: calc(100% - 32px);
    border: 2px solid #fc3c44;
    border-radius: 7px;
    background-color: rgba(32, 35, 42, 0.7);
    color: aliceblue;
    margin-right: 10px;
    outline: none;
    transition: border-color 0.3s ease, box-shadow 0.3s ease;
}

.recommendation-form-modal input[type="text"]:focus {
    border-color: #f94c57;
    box-shadow: 0 0 8px rgba(252, 60, 68, 0.4);
}

.recommendation-form-modal input[type="text"]:hover {
    border-color: #f94c57;
}

.recommendation-form-modal button {
    padding: 10px 15px;
    border: 2px solid transparent;
    border-radius: 7px;
    background-color: #fc3c44;
    color: white;
    cursor: pointer;
    transition: background-color 0.3s ease, color 0.3s ease, box-shadow 0.3s ease, border-color 0.3s ease;
}

.recommendation-form-modal button:focus,
.recommendation-form-modal button:hover {
    background-color: #f94c57;
    color: #ffffff;
    box-shadow: 0 0 8px rgba(252, 60, 68, 0.6);
    border-color: #f94c57;
}

.recommendation-form-modal button:focus {
    outline: 4px auto -webkit-focus-ring-color;
}

@media (max-width: 680px) {
    .recommendation-form-modal {
        width: 80vw;
        max-width: none;
    }

    .recommendation-form-modal form {
        flex-direction: column;
    }

    .recommendation-form-modal input[type="text"] {
        margin-right: 0;
        margin-bottom: 10px;
    }
}
</style>

// src/frontend/music-svelte/src/lib/RecommendationForm.svelte
<script lang="ts">
    // Prop passed from parent component
    export let onRecommend: (songTitle: string) => void;

    // Local state for the song title input
    let songTitle = "";

    // Handle form submission
    const handleSubmit = () => {
        onRecommend(songTitle);
        songTitle = ""; // Reset input field after submission
    };
</script>

<div class="recommendation-form-modal">
    <h1>Recommend a Song</h1>
    <form on:submit|preventDefault={handleSubmit}>
        <input
            type="text"
            bind:value={songTitle}
            placeholder="Find a song on Apple Music..."
            required
        />
        <button type="submit">Recommend</button>
    </form>
</div>

<style>
    .recommendation-form-modal {
        background: rgba(50, 50, 50, 0.6);
        color: aliceblue;
        padding: 20px;
        border-radius: 15px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        max-width: 600px;
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        box-shadow: inset 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .recommendation-form-modal h1 {
        width: 100%;
        text-align: left;
        margin-top: 0;
        margin-bottom: 10px;
    }

    .recommendation-form-modal form {
        width: 100%;
        display: flex;
    }

    .recommendation-form-modal input[type="text"] {
        padding: 10px 15px;
        width: calc(100% - 32px);
        border: 2px solid #fc3c44;
        border-radius: 7px;
        background-color: rgba(32, 35, 42, 0.7);
        color: aliceblue;
        margin-right: 10px;
        outline: none;
        transition:
            border-color 0.3s ease,
            box-shadow 0.3s ease;
    }

    .recommendation-form-modal input[type="text"]:focus {
        border-color: #f94c57;
        box-shadow: 0 0 8px rgba(252, 60, 68, 0.4);
    }

    .recommendation-form-modal input[type="text"]:hover {
        border-color: #f94c57;
    }

    .recommendation-form-modal button {
        padding: 10px 15px;
        border: 2px solid transparent;
        border-radius: 7px;
        background-color: #fc3c44;
        color: white;
        cursor: pointer;
        transition:
            background-color 0.3s ease,
            color 0.3s ease,
            box-shadow 0.3s ease,
            border-color 0.3s ease;
    }

    .recommendation-form-modal button:focus,
    .recommendation-form-modal button:hover {
        background-color: #f94c57;
        color: #ffffff;
        box-shadow: 0 0 8px rgba(252, 60, 68, 0.6);
        border-color: #f94c57;
    }

    .recommendation-form-modal button:focus {
        outline: 4px auto -webkit-focus-ring-color;
    }

    @media (max-width: 680px) {
        .recommendation-form-modal {
            width: 80vw;
            max-width: none;
        }

        .recommendation-form-modal form {
            flex-direction: column;
        }

        .recommendation-form-modal input[type="text"] {
            margin-right: 0;
            margin-bottom: 10px;
        }
    }
</style>
