// src/app/frontend/music/music-svelte/src/lib/NowPlaying.svelte
<script lang="ts">
    import type { Song } from "../types/Song";
    import placeholderAlbumCover from "../assets/300.png";

    const currentSong: Song = {
        songTitle: "Song Title",
        artistName: "Artist",
        albumName: "Album",
        albumCoverUrl: placeholderAlbumCover,
    };
</script>

<div class="now-playing-component styled-container">
    <img src={currentSong.albumCoverUrl} alt="Album Art" />
    <div class="now-playing-component-text-container">
        <h1>Mario's Now Playing</h1>
        <div class="now-playing-component-text">
            <h2>{currentSong.songTitle}</h2>
            <p>{currentSong.artistName}</p>
            <p>{currentSong.albumName}</p>
        </div>
    </div>
</div>

<style>
    .now-playing-component {
        display: flex;
        align-items: center;
        justify-content: flex-start;
    }

    .now-playing-component img {
        width: var(--album-art-size-large);
        height: var(--album-art-size-large);
        border-radius: 10px;
        margin-right: var(--margin-large);
    }

    .now-playing-component-text-container {
        flex-grow: 1;
        display: flex;
        flex-direction: column;
        justify-content: space-between;

        height: var(--album-art-size-large);
        /* Matching the size of the album art */
    }

    .now-playing-component h1 {
        margin: 0;
    }

    .now-playing-component-text {
        text-align: left;
    }

    .now-playing-component-text h2,
    .now-playing-component-text p {
        margin: 0;
    }

    @media (max-width: 680px) {
        .now-playing-component,
        .now-playing-component h1,
        .now-playing-component img,
        .now-playing-component-text {
            width: var(--width-mobile);
        }

        .now-playing-component {
            flex-direction: column-reverse;
            max-width: none;
        }

        .now-playing-component img {
            height: auto;
            margin: var(--margin-medium) 0;
        }

        .now-playing-component h1 {
            margin-bottom: var(--margin-medium);
        }

        .now-playing-component-text-container {
            height: auto;
        }
    }
</style>

// src/frontend/music-vue/src/components/NowPlaying.vue
<template>
    <div class="now-playing-component styled-container">
        <img :src="currentSong.albumCoverUrl" alt="Album Art" />
        <div class="now-playing-component-text-container">
            <h1>Mario's Now Playing</h1>
            <div class="now-playing-component-text">
                <h2>{{ currentSong.songTitle }}</h2>
                <p>{{ currentSong.artistName }}</p>
                <p>{{ currentSong.albumName }}</p>
            </div>
        </div>
    </div>
</template>
  
<script lang="ts">
import placeholderAlbumCover from '../assets/300.png';

export default {
    name: 'NowPlaying',
    data() {
        return {
            currentSong: {
                songTitle: "Song Title",
                artistName: "Artist",
                albumName: "Album",
                albumCoverUrl: placeholderAlbumCover
            }
        };
    }
};
</script>
  
<style>
.now-playing-component {
    display: flex;
    align-items: center;
    justify-content: flex-start;
}

.now-playing-component img {
    width: var(--album-art-size-large);
    height: var(--album-art-size-large);
    border-radius: 10px;
    margin-right: var(--margin-large);
}

.now-playing-component-text-container {
    flex-grow: 1;
    display: flex;
    flex-direction: column;
    justify-content: space-between;

    height: var(--album-art-size-large);
    /* Matching the size of the album art */
}

.now-playing-component h1 {
    margin: 0;
}

.now-playing-component-text {
    text-align: left;
}

.now-playing-component-text h2,
.now-playing-component-text p {
    margin: 0;
}

@media (max-width: 680px) {

    .now-playing-component,
    .now-playing-component h1,
    .now-playing-component img,
    .now-playing-component-text {
        width: var(--width-mobile);
    }

    .now-playing-component {
        flex-direction: column-reverse;
        max-width: none;
    }

    .now-playing-component img {
        height: auto;
        margin: var(--margin-medium) 0;
    }

    .now-playing-component h1 {
        margin-bottom: var(--margin-medium);
    }

    .now-playing-component-text-container {
        height: auto;
    }
}
</style>
