// src/app/frontend/music/music-next/src/App.tsx
import cx from "classix";
import React, { lazy, Suspense } from "react";
import AnimatedBackground from "./components/AnimatedBackground/AnimatedBackground";
import Footer from "./components/Footer/Footer";
import Navbar from "./components/Navbar/Navbar";
import NowPlaying from "./components/NowPlaying/NowPlaying";
import SkeletonLoader from "./components/RecentlyPlayedList/components/SkeletonLoader";
import recentlyPlayedStyles from "./components/RecentlyPlayedList/styles/RecentlyPlayedList.module.css";
import { useMusicContext } from "./context/MusicContext";
import { MusicProvider } from "./providers/MusicProvider";
import styles from "./styles/App.module.css";

// Lazy load heavy components to reduce initial bundle size
// Reference: https://react.dev/reference/react/lazy
const RecentlyPlayedList = lazy(
  () => import("./components/RecentlyPlayedList/RecentlyPlayedList"),
);

const AppContent: React.FC = () => {
  const { gradientColors } = useMusicContext();

  return (
    <>
      <AnimatedBackground colors={gradientColors} />
      <div className={styles.app}>
        <Navbar />
        <main className={styles.mainContent} role="main">
          <div className={styles.centerColumn}>
            <article
              className={cx(styles.nowPlayingContainer, styles.styledContainer)}
              aria-label="Currently playing song"
            >
              <NowPlaying />
            </article>
            <section
              className={cx(
                styles.recentlyPlayedContainer,
                styles.styledContainer,
              )}
              aria-label="Recently played songs"
            >
              <Suspense
                fallback={
                  <div
                    className={recentlyPlayedStyles.recentlyPlayedListComponent}
                    aria-busy="true"
                  >
                    <h1>Recently Played</h1>
                    <SkeletonLoader />
                  </div>
                }
              >
                <RecentlyPlayedList />
              </Suspense>
            </section>
          </div>
        </main>
        <Footer />
      </div>
    </>
  );
};

const App: React.FC = () => {
  return (
    <MusicProvider>
      <AppContent />
    </MusicProvider>
  );
};

export default App;

// src/app/frontend/music/music-vue/src/App.vue
<template>
  <AnimatedBackground :colors="gradientColors" />
  <div :class="styles.app">
    <Navbar />
    <main :class="styles.mainContent">
      <div :class="styles.centerColumn">
        <article
          :class="[styles.nowPlayingContainer, styles.styledContainer]"
          aria-label="Currently playing song"
        >
          <NowPlaying />
        </article>
        <section
          :class="[styles.recentlyPlayedContainer, styles.styledContainer]"
          aria-label="Recently played songs"
        >
          <RecentlyPlayedList />
        </section>
      </div>
    </main>
    <Footer />
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import AnimatedBackground from "./components/AnimatedBackground.vue";
import Footer from "./components/Footer.vue";
import Navbar from "./components/Navbar.vue";
import NowPlaying from "./components/NowPlaying.vue";
import RecentlyPlayedList from "./components/RecentlyPlayedList.vue";
import { provideMusicStore } from "./composables/useMusicStore";
import styles from "./styles/App.module.css";

const musicStore = provideMusicStore();
const gradientColors = computed(() => musicStore.gradientColors.value);
</script>
