// src/app/frontend/music/music-preact/src/app.tsx
import "./app.css";
import AnimatedBackground from "./components/AnimatedBackground";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import NowPlaying from "./components/NowPlaying";
import RecentlyPlayedList from "./components/RecentlyPlayedList";
import { useMusicStore } from "./hooks/useMusicStore";

export function App() {
  const { nowPlaying, recentlyPlayed, loading, error, gradientColors } = useMusicStore();

  return (
    <>
      <AnimatedBackground colors={gradientColors} />
      <div className="app">
        <Navbar />
        <main className="main-content" role="main">
          <div className="center-column">
            <div className="now-playing-container styled-container">
              <NowPlaying nowPlaying={nowPlaying} loading={loading} error={error} />
            </div>
            <div className="recently-played-container styled-container">
              <RecentlyPlayedList
                recentlyPlayed={recentlyPlayed}
                loading={loading}
                error={error}
              />
            </div>
          </div>
        </main>
        <Footer />
      </div>
    </>
  );
}

// src/app/frontend/music/music-vue/src/App.vue
<template>
  <AnimatedBackground :colors="gradientColors" />
  <div :class="styles.app">
    <Navbar />
    <main :class="styles.mainContent">
      <div :class="styles.centerColumn">
        <article
          :class="[styles.nowPlayingContainer, styles.styledContainer]"
          aria-label="Currently playing song"
        >
          <NowPlaying />
        </article>
        <section
          :class="[styles.recentlyPlayedContainer, styles.styledContainer]"
          aria-label="Recently played songs"
        >
          <RecentlyPlayedList />
        </section>
      </div>
    </main>
    <Footer />
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import AnimatedBackground from "./components/AnimatedBackground.vue";
import Footer from "./components/Footer.vue";
import Navbar from "./components/Navbar.vue";
import NowPlaying from "./components/NowPlaying.vue";
import RecentlyPlayedList from "./components/RecentlyPlayedList.vue";
import { provideMusicStore } from "./composables/useMusicStore";
import styles from "./styles/App.module.css";

const musicStore = provideMusicStore();
const gradientColors = computed(() => musicStore.gradientColors.value);
</script>
