// src/frontend/music-angular/src/app/components/navbar/navbar.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css'
})
export class NavbarComponent { }

<nav class="navbar">
    <a href="https://music.mariolopez.org/lit" target="_self" rel="alternate">
        <img src="/assets/images/lit.svg" alt="Lit" class="nav-icon" />
    </a>
    <a href="https://music.mariolopez.org/qwik" target="_self" rel="alternate">
        <img src="/assets/images/qwik.svg" alt="Qwik" class="nav-icon" />
    </a>
    <a href="https://music.mariolopez.org/react" target="_self" rel="alternate">
        <img src="/assets/images/react.svg" alt="React" class="nav-icon" />
    </a>
    <a href="https://music.mariolopez.org/solid" target="_self" rel="alternate">
        <img src="/assets/images/solid.svg" alt="Solid" class="nav-icon" />
    </a>
    <a href="https://music.mariolopez.org/svelte" target="_self" rel="alternate">
        <img src="/assets/images/svelte.svg" alt="Svelte" class="nav-icon" />
    </a>
    <a href="https://music.mariolopez.org/vanilla" target="_self" rel="alternate">
        <img src="/assets/images/typescript.svg" alt="TypeScript" class="nav-icon" />
    </a>
    <a href="https://music.mariolopez.org/vue" target="_self" rel="alternate">
        <img src="/assets/images/vue.svg" alt="Vue" class="nav-icon" />
    </a>
    <a href="https://music.mariolopez.org/preact" target="_self" rel="alternate">
        <img src="/assets/images/preact.svg" alt="Preact" class="nav-icon" />
    </a>
    <a href="https://music.mariolopez.org/next" target="_self" rel="alternate">
        <img src="/assets/images/next.svg" alt="Next" class="nav-icon" />
    </a>
    <a href="https://music.mariolopez.org/angular" target="_self" rel="alternate">
        <img src="/assets/images/angular.svg" alt="Angular" class="nav-icon angular-icon" />
    </a>
</nav>

// src/frontend/music-next/src/components/Navbar/index.tsx
import React from 'react';
import Image from 'next/image';
import styles from './style.module.css';

const Navbar: React.FC = () => {
    return (
        <nav className={styles.navbar}>
            <a href="https://music.mariolopez.org/lit" target="_self" rel="alternate">
                <Image src="/images/lit.svg" alt="Lit" width={40} height={40} className={styles.navIcon} />
            </a>
            <a href="https://music.mariolopez.org/qwik" target="_self" rel="alternate">
                <Image src="/images/qwik.svg" alt="Qwik" width={40} height={40} className={styles.navIcon} />
            </a>
            <a href="https://music.mariolopez.org/react" target="_self" rel="alternate">
                <Image src="/images/react.svg" alt="React" width={40} height={40} className={styles.navIcon} />
            </a>
            <a href="https://music.mariolopez.org/solid" target="_self" rel="alternate">
                <Image src="/images/solid.svg" alt="Solid" width={40} height={40} className={styles.navIcon} />
            </a>
            <a href="https://music.mariolopez.org/svelte" target="_self" rel="alternate">
                <Image src="/images/svelte.svg" alt="Svelte" width={40} height={40} className={styles.navIcon} />
            </a>
            <a href="https://music.mariolopez.org/vanilla" target="_self" rel="alternate">
                <Image src="/images/typescript.svg" alt="TypeScript" width={40} height={40} className={styles.navIcon} />
            </a>
            <a href="https://music.mariolopez.org/vue" target="_self" rel="alternate">
                <Image src="/images/vue.svg" alt="Vue" width={40} height={40} className={styles.navIcon} />
            </a>
            <a href="https://music.mariolopez.org/preact" target="_self" rel="alternate">
                <Image src="/images/preact.svg" alt="Preact" width={40} height={40} className={styles.navIcon} />
            </a>
            <a href="https://music.mariolopez.org/next" target="_self" rel="alternate">
                <Image src="/images/next.svg" alt="Next" width={40} height={40} className={`${styles.navIcon} ${styles.nextIcon}`} />
            </a>
        </nav>
    );
};

export default Navbar;
